spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wca_development
    username: root
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
api:
  wca:
    baseurl: http://localhost:3500
server:
  port: 8081