version: "3.1"
services:
  wca-test-db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: wca_development
    ports:
      - "3307:3306"
    volumes:
      - "./db/migration:/docker-entrypoint-initdb.d/:ro"
      - wca-test-db-data:/var/lib/mysql

volumes:
  wca-test-db-data:
