name: Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/backtest.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore gradle dependencies
        uses: actions/cache@v4
        with:
          path: "~/.gradle"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/build.gradle.kts') }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Run containers
        run: docker compose -f docker-compose-test.yaml up -d
      - name: Wait for database to start
        run: |
          for i in `seq 1 60`;
          do
            nc -z localhost 3307 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for mysql && exit 1
      - name: Build and test
        run: ./gradlew clean build --info
