name: Frontend

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/fronttest.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/fronttest.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: "**/client/node_modules"
          key: ${{ runner.os }}-v2-${{ hashFiles('**/client/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npx prettier --check .
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm test
